### ISSUE TITLE
Crash when writing in Japanese

### ISSUE THREAD

**Issue by Belarrius1** [LostRuins/llamacpp-for-kobold#9]
Hello, I asked my AI for a translation into Japanese and it caused a crash. Here is the report:

```
Exception occurred during processing of request from ('192.168.1.254', 50865)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/llamacpp-for-kobold/llamacpp_for_kobold.py", line 98, in __call__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.10/http/server.py", line 658, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/home/llamacpp-for-kobold/llamacpp_for_kobold.py", line 189, in do_POST
    recvtxt = generate(
  File "/home/llamacpp-for-kobold/llamacpp_for_kobold.py", line 76, in generate
    return ret.text.decode("UTF-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 21: unexpected end of data
```

I use the latest git of llamacpp-for-kobold, with Ubuntu Server 22.04.2 LTS, hardware: i7 10750H, 64GB of RAM

**Comment by Belarrius1** [comment]
![image](https://user-images.githubusercontent.com/129199373/228819079-abe085ea-2a41-4f02-a523-4cb743ece923.png)

![image](https://user-images.githubusercontent.com/129199373/228819152-cebee22b-2a03-4f88-ad38-a11386cb4190.png)

**Comment by Belarrius1** [comment]
I change all "utf-8" by "ISO-8859-1" in llamacpp_for_kobold.py and it's works now

**Comment by Belarrius1** [comment]
Ok, I speak too quickly, now, I have this "trè±¨mpÃ©." i waill wait you for this because i'm not dev ahah

**Comment by LostRuins** [comment]
The issue has been resolved, the fix will be available in the next release.

**Comment by LostRuins** [comment]
Hi, newest build with this solved is ready. You can get it at https://github.com/LostRuins/llamacpp-for-kobold/releases/

**Comment by Belarrius1** [comment]
I already tested before the release with cloning the git and it's perfect! THANKS ! :p
